name: wmbt
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.0.1
  flutter_switch: ^0.3.2
  flutter_bloc: ^8.0.1
  provider: ^6.0.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.11
  dropdown_button2: ^2.1.0
  persistent_bottom_nav_bar: ^5.0.2
  dio: ^5.1.2
  get: ^4.6.5
  syncfusion_flutter_charts: ^21.2.4
  custom_pop_up_menu: ^1.2.4
  intl: ^0.17.0
  convex_bottom_bar: ^3.2.0
  qr_flutter: ^4.0.0
  pin_code_fields: ^7.4.0
  device_info: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0
#dependency_overrides:
#  intl: ^0.18.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Book.ttf

        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 600

        - asset: assets/fonts/CircularStd-Black.ttf
          weight: 700

        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 900

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "color you want for android adaptive icon background"
  adaptive_icon_foreground: "assets/app_icon.png"
flutter_intl:
  enabled: true
